name: Run Tests

on:
  # tests can be called from other workflows
  workflow_call:

  # always run tests for every push to master
  push:
    branches: [master]

  # always run tests for every PR
  pull_request:
    branches: [master]

jobs:
  pre-commit:
    name: Run code checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          # renovate: datasource=python-version depName=python versioning=python
          python-version: 3.11
      - uses: pre-commit/action@v2.0.3

  unittest:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          # renovate: datasource=python-version depName=python versioning=python
          python-version: 3.11
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          # renovate: datasource=pypi depName=poetry versioning=pep440
          poetry-version: 1.5.1
      - name: Install dependencies
        run: poetry install --no-dev
      - name: Run unit tests
        run: poetry run python -m unittest discover
